source "https://rubygems.org"

gem "bootsnap", require: false
gem "discard"
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "propshaft"
gem "pagy", "~> 9.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rails", "~> 8.1.3"
gem "ransack"
gem "redis"
gem "sidekiq"
gem "simple_form"
gem "solid_cache"
gem "solid_cable"
gem "solid_queue"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development do
  gem "letter_opener_web"
  gem "overcommit"
end

group :development, :test do
  gem "annotaterb"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "capybara"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-rails"
  gem "rubocop-rails-omakase", require: false
  gem "selenium-webdriver"
  gem "shoulda-matchers"
end
