source "https://rubygems.org"

gem "bootsnap", require: false
gem "dotenv-rails"
gem "grape"
gem "grape-entity"
gem "grape-swagger"
gem "grape-swagger-rails"
gem "pagy"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "rails", "~> 8.1.3"
gem "solid_cache"
gem "solid_cable"
gem "solid_queue"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "annotaterb"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "factory_bot_rails"
  gem "rubocop-rails-omakase", require: false
  gem "shoulda-matchers"
end
